#!/usr/bin/env bash

# Preferred editor for local and remote sessions
export EDITOR='hx'
export SUDO_EDITOR="$HOME/.cargo/bin/hx"

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

export DEV_HOME=$HOME/Dev

# Golang
export GOPATH=$HOME/go

# Rust
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

# Python
export PYTHONPATH="$PYTHONPATH:/usr/lib/llvm-4.0/lib/python2.7/site-packages"
export PYTHONSTARTUP=$HOME/.pythonrc

# Fuchsia
export FUCHSIA_SDK_DIR=/google/src/head/depot/google3/third_party/unsupported_toolchains/fuchsia/sdk
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

# CastOS
export USE_GOMA=1

# nnn
export NNN_FIFO=/tmp/nnn.fifo
export NNN_PLUG='f:finder;o:fzopen;p:preview-tui;d:diffs'

# Helix
export HELIX_RUNTIME=~/Dev/helix/runtime

# wayland
export XDG_SESSION_TYPE=wayland
export QT_WAYLAND_FORCE_DPI=physical
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
